#!/usr/bin/env python3
# genfont.py - extract a console font (PSF1/PSF2, width <= 8) into a C header.
# Emits font.h with:
#     #define FONT_W <w>
#     #define FONT_H <h>
#     static const unsigned char fontdata[256][<h>];   // 1 byte/row, MSB=left pixel
# Uses a real system console font (no hand-authored glyphs). Run on the Pi.
#
# Default picks a 6x12 Terminus (=> 80 columns on the 480px axis). Override with a
# font name/path as argv[1].
#   python3 genfont.py > font.h
#   python3 genfont.py Lat15-VGA16 > font.h     # 8x16 (60 cols landscape)

import gzip, os, struct, sys

FONTDIR = "/usr/share/consolefonts"
# Preference: narrow 6x12 first (80 cols), then classic 8x16 latin VGA (60 cols).
CANDIDATES = [
    "Lat15-Terminus12x6", "Lat2-Terminus12x6", "Lat7-Terminus12x6", "Uni2-Terminus12x6",
    "Lat15-VGA16", "Lat2-VGA16", "Lat15-Fixed16", "Uni2-VGA16",
]

def read_bytes(path):
    with open(path, "rb") as f:
        raw = f.read()
    if path.endswith(".gz") or raw[:2] == b"\x1f\x8b":
        raw = gzip.decompress(raw)
    return raw

def resolve(name):
    if os.path.exists(name):
        return name
    for ext in ("", ".psf.gz", ".psf", ".psfu.gz", ".psfu"):
        p = os.path.join(FONTDIR, name + ext)
        if os.path.exists(p):
            return p
    return None

def parse_psf(raw):
    """Return (num_glyphs, height, width, charsize, glyph_offset)."""
    if raw[:2] == b"\x36\x04":                     # PSF1
        mode, charsize = raw[2], raw[3]
        num = 512 if (mode & 0x01) else 256
        return num, charsize, 8, charsize, 4
    if raw[:4] == b"\x72\xb5\x4a\x86":             # PSF2
        (ver, hdr, flags, length, charsize, height, width) = struct.unpack("<7I", raw[4:32])
        return length, height, width, charsize, hdr
    raise ValueError("not a PSF1/PSF2 font")

def load_font(path):
    raw = read_bytes(path)
    num, height, width, charsize, off = parse_psf(raw)
    if width > 8:
        raise ValueError(f"{path}: width {width} > 8 unsupported (1 byte/row)")
    bpr = (width + 7) // 8  # =1 for width <= 8
    glyphs = []
    for i in range(min(num, 256)):
        g = raw[off + i*charsize : off + i*charsize + charsize]
        rows = [g[j*bpr] if j*bpr < len(g) else 0 for j in range(height)]
        glyphs.append(rows)
    while len(glyphs) < 256:
        glyphs.append([0]*height)
    return glyphs, width, height

def main():
    chosen = None
    if len(sys.argv) > 1:
        chosen = resolve(sys.argv[1])
        if not chosen:
            sys.exit(f"font not found: {sys.argv[1]}")
    else:
        for name in CANDIDATES:
            p = resolve(name)
            if p:
                try:
                    load_font(p); chosen = p; break
                except Exception:
                    continue
    if not chosen:
        sys.exit("no suitable font found in " + FONTDIR)

    glyphs, w, h = load_font(chosen)
    out = sys.stdout
    out.write("// Auto-generated by genfont.py from " + os.path.basename(chosen) + "\n")
    out.write("// %dx%d bitmap font, 256 glyphs, 1 byte per row (MSB = leftmost pixel).\n" % (w, h))
    out.write("#ifndef KEDEICON_FONT_H\n#define KEDEICON_FONT_H\n")
    out.write("#define FONT_W %d\n#define FONT_H %d\n" % (w, h))
    out.write("static const unsigned char fontdata[256][%d] = {\n" % h)
    for rows in glyphs:
        out.write("  {%s},\n" % ",".join("0x%02x" % b for b in rows))
    out.write("};\n#endif\n")
    sys.stderr.write("genfont.py: used %s (%dx%d)\n" % (chosen, w, h))

if __name__ == "__main__":
    main()
